development:
  adapter: postgresql
  encoding: unicode
  database: micah_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: micah_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: micah_production
  pool: 5
